# This file is auto-generated by .github/workflows/update-francis.yaml
# Do not edit manually - changes will be overwritten on the next release

class Francis < Formula
  desc "CLI for rigorous A/B performance testing on Android"
  homepage "https://github.com/block/francis"
  url "https://github.com/block/francis/releases/download/v0.0.11/francis-release.tar.gz"
  sha256 "1a5340d95697dbcb85fe4b01e9ddd3c64185c7845113d7cf72989ae12c71e7d6"
  license "Apache-2.0"
  version "0.0.11"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/jvm/francis"
  end

  test do
    system "#{bin}/francis", "--help"
  end
end
