# This file is auto-generated by .github/workflows/update-francis.yaml
# Do not edit manually - changes will be overwritten on the next release

class Francis < Formula
  desc "CLI for rigorous A/B performance testing on Android"
  homepage "https://github.com/block/francis"
  url "https://github.com/block/francis/releases/download/v0.0.14/francis-release.tar.gz"
  sha256 "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
  license "Apache-2.0"
  version "0.0.14"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/jvm/francis"
  end

  test do
    system "\#{bin}/francis", "--help"
  end
end
