# This file is auto-generated by .github/workflows/update-qrgo.yaml
# Do not edit manually - changes will be overwritten on the next release

class Qrgo < Formula
  desc "A CLI utility for screen-capturing a QR code and launching it in an Android emulator or iOS simulator."
  homepage "https://github.com/block/qrgo"
  url "https://github.com/block/qrgo/releases/download/1.0.2/qrgo-release.tar.gz"
  sha256 "2f7d8940108b69a675780a4f2a49ff770c75d084413a7166bc359e1cbb5d466b"
  license "Apache-2.0"
  version "1.0.2"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"qrgo"
  end

  test do
    system "\#{bin}/qrgo", "--help"
  end
end
