# This file is auto-generated by .github/workflows/update-qrgo.yaml
# Do not edit manually - changes will be overwritten on the next release

class Qrgo < Formula
  desc "A CLI utility for screen-capturing a QR code and launching it in an Android emulator or iOS simulator."
  homepage "https://github.com/block/qrgo"
  url "https://github.com/block/qrgo/releases/download/1.0.0/qrgo-release.tar.gz"
  sha256 "98493fecc23de49c63c69f0f8c6a07253ec339e816b71878229ab839214d217f"
  license "Apache-2.0"
  version "1.0.0"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"qrgo"
  end

  test do
    system "\#{bin}/qrgo", "--help"
  end
end
