# This file is auto-generated by .github/workflows/update-stoic.yaml
# Do not edit manually - changes will be overwritten on the next release

class Stoic < Formula
  desc "CLI tool for Android investigations"
  homepage "https://github.com/block/stoic"
  url "https://github.com/block/stoic/releases/download/v0.9.0/stoic-release.tar.gz"
  sha256 "48e251c2192aa914dc6d1b77903a8982e287ac1b941fa5d6394479aed63dbcdd"
  license "Apache-2.0"
  version "0.9.0"

  def install
    libexec.install Dir["*"]

    # Use native binary for macOS ARM64, JVM version for everything else
    if OS.mac? && Hardware::CPU.arm?
      bin.install_symlink libexec/"bin/darwin-arm64/stoic"
    else
      bin.install_symlink libexec/"bin/jvm/stoic"
    end
  end

  test do
    system "\#{bin}/stoic", "--help"
  end
end
