# This file is auto-generated by .github/workflows/update-stoic.yaml
# Do not edit manually - changes will be overwritten on the next release

class Stoic < Formula
  desc "CLI tool for Android investigations"
  homepage "https://github.com/block/stoic"
  url "https://github.com/block/stoic/releases/download/v0.6.2/stoic-release.tar.gz"
  sha256 "a13d781869a4c8acad5dfd1654d2bc97bbfb244104a8506e4a052539941596f4"
  license "Apache-2.0"
  version "0.6.2"

  def install
    libexec.install Dir["*"]

    # Use native binary for macOS ARM64, JVM version for everything else
    if OS.mac? && Hardware::CPU.arm?
      bin.install_symlink libexec/"bin/darwin-arm64/stoic"
    else
      bin.install_symlink libexec/"bin/jvm/stoic"
    end
  end

  test do
    system "\#{bin}/stoic", "--help"
  end
end
