# This file is auto-generated by .github/workflows/update-stoic.yml
# Do not edit manually - changes will be overwritten on the next release

class Stoic < Formula
  desc "CLI tool for Android investigations"
  homepage "https://github.com/block/stoic"
  url "https://github.com/block/stoic/releases/download/v0.6.0/stoic-release.tar.gz"
  sha256 "f8527b3c91ea317c7153ea270207458690913bccdc597b69bb093de18a35a6ae"
  license "Apache-2.0"
  version "0.6.0"

  def install
    libexec.install Dir["*"]

    # Use native binary for macOS ARM64, JVM version for everything else
    if OS.mac? && Hardware::CPU.arm?
      bin.install_symlink libexec/"bin/darwin-arm64/stoic"
    else
      bin.install_symlink libexec/"bin/jvm/stoic"
    end
  end

  test do
    system "#{bin}/stoic", "--help"
  end
end
